services:
  server:
    build: .
    depends_on:
      - worker
      - dashboard
    ports:
      - 8080:8000
    env_file:
      - .env
    volumes:
      - .:/app
  worker:
    build: .
    depends_on:
      - redis
    command:
      - celery
      - --app=tasks.celery
      - worker
      - --loglevel=info
    env_file:
      - .env
  dashboard:
    build: .
    depends_on:
      - redis
    command:
      - celery
      - --app=tasks.celery
      - flower
      - --port=5555
    ports:
      - 5555:5555
    env_file:
      - .env
  redis:
    image: redis:latest
